CREATE TABLE clienti (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 cognome VARCHAR(128),
 username VARCHAR(128),
 password VARCHAR(128),
 email VARCHAR(128),
 indirizzo VARCHAR(128),
 saldo_cliente REAL);

CREATE TABLE venditori (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 cognome VARCHAR(128),
 username VARCHAR(128),
 password VARCHAR(128),
 email VARCHAR(128),
 indirizzo VARCHAR(128),
 saldo_venditore REAL);

CREATE TABLE oggetti (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 descrizione VARCHAR(128),
 categoria VARCHAR(128),
 quantita INTEGER,
 url_immagine VARCHAR(128),
 prezzo REAL,
 id_venditore INTEGER,
 FOREIGN KEY (id_venditore) REFERENCES venditori(id));